### ISSUE TITLE
Set up postman

### ISSUE THREAD

**Issue by kennethchittaphong** [nss-evening-cohort-19/rare-client-the-good-name-team#2]
Set up requesthandler class to include all the necessary HTTP request methods (GET, POST, PUT, DELETE)
Set classes for models

**Comment by cod-y-clark** [comment]
CRUD for the Posts & Categories are completed

**Comment by gavinschriver** [comment]
* Posts, Categories,  with full CRUD in backend; soon to follow with Comments (Nick) PostTags and Tags (Tatiana)
